name: Sync Blog to Gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 仅允许读取仓库内容
      gists: write    # 仅允许操作 Gist
    steps:
      - name: Checkout sync repo
        uses: actions/checkout@v3
        with:
          path: main-repo

      - name: Checkout blog repo
        uses: actions/checkout@v3
        with:
          repository: BH3GEI/blog
          path: blog
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 明确指定版本

      - name: Install dependencies
        run: pip install PyGithub

      - name: Sync to Gist
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}  # 修改变量名
        run: |
          cd main-repo
          python .github/scripts/sync_to_gist.py
