name: Blog to Gist Sync (Raw Mode)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 仅需基础权限
      gists: write    # 必须的Gist权限

    steps:
    - name: Checkout Script Repo
      uses: actions/checkout@v4
      with:
        path: main-repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub==1.59.0 requests==2.31.0 tenacity==8.2.3

    - name: Run Sync Script
      env:
        GH_TOKEN: ${{ secrets.GIST_TOKEN }}  # 需要 repo 和 gist 权限的PAT
      run: |
        cd main-repo
        python .github/scripts/sync_to_gist.py
